apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
  labels:
    app: node-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: 860133/node-app:latest
        ports:
        - name: node-app-port
          containerPort: 3000
        resources:
          limits:
            cpu: "1"
          requests:
            cpu: 200m

---
apiVersion: v1
kind: Service
metadata:
  name: node-app-service
spec:
  ports:
  - port: 8080
#    nodePort: 31001
    targetPort: node-app-port
    protocol: TCP
  selector:
    app: node-app
  type: LoadBalancer

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-node-app-autoscaler
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: node-app
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
